# Generated by Django 4.1.2 on 2022-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('REVENDEDOR', 'Revendedor'), ('LOJA', 'Loja'), ('SUPERVISOR', 'Supervisor'), ('FRANQUIA', 'Franquia')], default='REVENDEDOR', max_length=50, null=True, verbose_name='tipo'),
        ),
    ]
