# Generated by Django 4.1.1 on 2022-09-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='revendedor',
            managers=[
            ],
        ),
    ]
