# Generated by Django 4.1.2 on 2022-11-09 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='criado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado'),
        ),
    ]
