# Generated by Django 4.1.2 on 2022-11-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_criado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, choices=[('revendedor', 'Revendedor'), ('loja', 'Loja'), ('supervisor', 'Supervisor'), ('franquia', 'Franquia')], default='revendedor', max_length=50, null=True, verbose_name='tipo'),
        ),
    ]
