# Generated by Django 4.1.2 on 2022-11-09 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(blank=True, max_length=150, verbose_name='razão social')),
                ('cnpj', models.IntegerField(blank=True, unique=True, verbose_name='cnpj')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(blank=True, max_length=150, verbose_name='razão social')),
                ('cnpj', models.IntegerField(blank=True, unique=True, verbose_name='cnpj')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('franquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.franquia', verbose_name='franquia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Bronze', 'bronze'), ('Prata', 'prata'), ('Ouro', 'ouro'), ('Diamante', 'diamante')], max_length=50)),
                ('valor', models.FloatField(verbose_name='valor')),
                ('desconto', models.FloatField(verbose_name='desconto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='codigo do produto')),
                ('descricao', models.CharField(max_length=200, null=True, verbose_name='descrição')),
                ('nome', models.CharField(max_length=100, null=True, unique=True, verbose_name='nome do produto')),
                ('qtde_estoque', models.PositiveIntegerField(null=True, verbose_name='quantidade em estoque')),
                ('preco', models.FloatField(null=True, verbose_name='preço do produto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='nome')),
                ('cpf', models.IntegerField(blank=True, unique=True, verbose_name='cpf')),
                ('franquia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.franquia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(blank=True, verbose_name='Cpf')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=15, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('datanasc', models.DateField(blank=True, verbose_name='Data de nascimento')),
                ('is_aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.meta')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.supervisor', verbose_name='supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revendedor',
                'verbose_name_plural': 'Revendedores',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pedido', models.CharField(max_length=100, null=True, verbose_name='código do pedido')),
                ('status', models.CharField(blank=True, choices=[('Aprovação pendente', 'Aprovacao_pendente'), ('Aprovado', 'aprovado'), ('Enviado', 'enviado'), ('Finalizado', 'finalizado')], max_length=50, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data do pedido')),
                ('subtotal', models.FloatField(blank=True, null=True, verbose_name='valor pré-desconto do pedido')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='valor total do pedido')),
                ('metodo_de_pagamento', models.CharField(blank=True, choices=[('credito', 'Credito'), ('debito', 'Debito'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=200, null=True)),
                ('franquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.franquia', verbose_name='franquia')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.loja', verbose_name='loja')),
                ('revendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.revendedor', verbose_name='revendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Nota_fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf', models.IntegerField(unique=True, verbose_name='nota fiscal')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='data de emissão')),
                ('inscricao_estadual', models.CharField(max_length=200, verbose_name='inscrição estadual')),
                ('razao_social', models.CharField(max_length=150, verbose_name='razão social')),
                ('cnpj', models.IntegerField(verbose_name='cnpj')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='nome fantasia')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.pedido', verbose_name='pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.produto', verbose_name='produto')),
            ],
        ),
        migrations.CreateModel(
            name='item_nf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='quantidade do produto')),
                ('qtde_faturada', models.IntegerField(verbose_name='quantidade faturada')),
                ('nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.nota_fiscal', verbose_name='pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.produto', verbose_name='produto')),
            ],
        ),
    ]
