# Generated by Django 4.1.1 on 2022-10-25 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=150, verbose_name='razão social')),
                ('cnpj', models.IntegerField(unique=True, verbose_name='cnpj')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=150, verbose_name='razão social')),
                ('cnpj', models.IntegerField(unique=True, verbose_name='cnpj')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('franquia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.franquia', verbose_name='franquia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='codigo do produto')),
                ('descricao', models.CharField(max_length=200, null=True, verbose_name='descrição')),
                ('nome', models.CharField(max_length=100, null=True, unique=True, verbose_name='nome do produto')),
                ('qtde_estoque', models.IntegerField(null=True, verbose_name='quantidade em estoque')),
                ('preco', models.FloatField(null=True, verbose_name='preço do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cpf', models.IntegerField(unique=True, verbose_name='cpf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('cpf', models.IntegerField(null=True, verbose_name='Cpf')),
                ('telefone', models.IntegerField(null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=200, null=True, verbose_name='Endereço')),
                ('datanasc', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('is_aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.supervisor', verbose_name='supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revendedor',
                'verbose_name_plural': 'Revendedores',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aprovação_pendente', 'Aprovação pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado')], max_length=50)),
                ('data', models.DateTimeField(verbose_name='data do pedido')),
                ('total', models.FloatField(verbose_name='valor total do pedido')),
                ('metodo_de_pagamento', models.CharField(choices=[('credito', 'Credito'), ('debito', 'Debito'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=200)),
                ('franquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.franquia', verbose_name='franquia')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.loja', verbose_name='loja')),
                ('revendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='revendedor')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.supervisor', verbose_name='supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Nota_fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf', models.IntegerField(unique=True, verbose_name='nota fiscal')),
                ('valor', models.FloatField(verbose_name='valor')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='data de emissão')),
                ('inscricao_estadual', models.CharField(max_length=200, verbose_name='inscrição estadual')),
                ('razao_social', models.CharField(max_length=150, verbose_name='razão social')),
                ('cnpj', models.IntegerField(verbose_name='cnpj')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='nome fantasia')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.pedido', verbose_name='pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('bronze', 'Bronzee'), ('prata', 'Prata'), ('ouro', 'Ouro'), ('diamante', 'Diamante')], max_length=50)),
                ('valor', models.FloatField(verbose_name='valor')),
                ('recompensa', models.CharField(max_length=150, verbose_name='recompensa')),
                ('Revendedor', models.ManyToManyField(to='vendas.revendedor', verbose_name='revendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Item_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.produto', verbose_name='produto')),
            ],
        ),
        migrations.CreateModel(
            name='item_nf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='quantidade do produto')),
                ('qtde_faturada', models.IntegerField(verbose_name='quantidade faturada')),
                ('nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.nota_fiscal', verbose_name='pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.produto', verbose_name='produto')),
            ],
        ),
    ]
