# Generated by Django 4.1.2 on 2022-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'iniciante'), ('Bronze', 'bronze'), ('Prata', 'prata'), ('Ouro', 'ouro'), ('Diamante', 'diamante')], max_length=50),
        ),
    ]
