# Generated by Django 4.1.1 on 2022-11-16 21:42

from django.db import migrations, models
import django.db.models.deletion
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='franquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.franquia', verbose_name='franquia'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='meta',
            field=models.ForeignKey(blank=True, default=vendas.models.Loja.meta_diamante, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.meta'),
        ),
    ]
