# Generated by Django 4.1.2 on 2022-11-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='franquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.franquia'),
        ),
    ]
