# Generated by Django 4.1.2 on 2022-11-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franquia',
            name='cnpj',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('aprovacao_pendente', 'Aprovação pendente'), ('aprovado', 'Aprovado'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aprovacao_pendente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='sexo',
            field=models.CharField(blank=True, choices=[('homem', 'Masculino'), ('mulher', 'Feminino'), ('outro', 'Outro')], max_length=30, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='sexo',
            field=models.CharField(blank=True, choices=[('homem', 'Masculino'), ('mulher', 'Feminino'), ('outro', 'Outro')], max_length=30, verbose_name='sexo'),
        ),
    ]
