# Generated by Django 4.1.1 on 2022-10-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_pedido',
            new_name='ItemPedido',
        ),
    ]
