# Generated by Django 4.1.1 on 2022-10-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=models.IntegerField(null=True, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='datanasc',
            field=models.DateField(null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='endereco',
            field=models.CharField(max_length=200, null=True, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='telefone',
            field=models.IntegerField(null=True, verbose_name='telefone'),
        ),
    ]
