# Generated by Django 4.1.2 on 2022-11-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_loja_franquia_alter_loja_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquia',
            name='is_aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='loja',
            name='is_aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='is_aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
