# Generated by Django 4.1.1 on 2022-10-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_revendedor_user_alter_supervisor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='quantidade do produto')),
                ('subtotal', models.IntegerField(verbose_name='subtotal')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido', verbose_name='pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.produto', verbose_name='produto')),
            ],
        ),
    ]
