# Generated by Django 4.1.2 on 2022-12-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_franquia_cnpj_alter_loja_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
