# Generated by Django 4.1.1 on 2022-10-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_revendedor_cpf_alter_revendedor_datanasc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revendedor',
            name='is_aprovado',
            field=models.BooleanField(default=False, verbose_name='aprovado'),
        ),
    ]
