# Generated by Django 4.1.2 on 2022-11-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_supervisor_franquia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('aprovacao_pendente', 'Aprovação pendente'), ('aprovado', 'Aprovado'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado')], max_length=50, null=True),
        ),
    ]
