# Generated by Django 4.1.1 on 2022-10-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_item_pedido_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_de_pagamento',
            field=models.CharField(blank=True, choices=[('credito', 'Credito'), ('debito', 'Debito'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('aprovação_pendente', 'Aprovação pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='valor total do pedido'),
        ),
    ]
