# Generated by Django 4.1.2 on 2022-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_remove_pedido_supervisor_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovação pendente', 'Aprovação pendente'), ('aprovado', 'Aprovado'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado')], max_length=50, null=True),
        ),
    ]
