# Generated by Django 4.1.1 on 2022-10-18 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0003_revendedor_is_aprovado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revendedor',
            options={'verbose_name': 'Revendedor', 'verbose_name_plural': 'Revendedores'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_de_pagamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='revendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='revendedor'),
        ),
    ]
