# Generated by Django 4.1.1 on 2022-10-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_item_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedido',
            name='quantidade',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
    ]
