# Generated by Django 4.1.1 on 2022-10-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='data do pedido'),
        ),
    ]
