# Generated by Django 4.1.2 on 2022-11-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='nivel',
            field=models.CharField(choices=[('Bronze', 'bronze'), ('Prata', 'prata'), ('Ouro', 'ouro'), ('Diamante', 'diamante')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovação pendente', 'Aprovacao_pendente'), ('Aprovado', 'aprovado'), ('Enviado', 'enviado'), ('Finalizado', 'finalizado')], max_length=50, null=True),
        ),
    ]
