# Generated by Django 4.1.2 on 2022-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_meta_nivel_alter_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='recompensa',
        ),
        migrations.AddField(
            model_name='meta',
            name='desconto',
            field=models.FloatField(default=1, verbose_name='desconto'),
            preserve_default=False,
        ),
    ]
