# Generated by Django 4.1.1 on 2022-10-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_itempedido_pedido_alter_itempedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='revendedor',
            name='cep',
            field=models.CharField(max_length=15, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='telefone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
