# Generated by Django 4.1.1 on 2022-10-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_revendedor_cep_alter_revendedor_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='Revendedor',
        ),
        migrations.AddField(
            model_name='revendedor',
            name='meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.meta'),
        ),
    ]
