# Generated by Django 4.1.2 on 2022-11-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_remove_meta_recompensa_meta_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(blank=True, null=True, verbose_name='valor pré-desconto do pedido'),
        ),
    ]
