# Generated by Django 4.1.2 on 2022-11-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_pedido_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='data do pedido'),
        ),
    ]
