# Generated by Django 4.1.2 on 2022-11-07 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data do pedido'),
        ),
    ]
